### ISSUE TITLE
Question, I googled but can't find out the exactly answer.

### ISSUE THREAD

**Issue by Doimatcuabautroi** [amitxv/TimerResolution#3]
Is there any way to force a timer resolution value for windows? or a 'global' value for all processes, except some process like wmplayer, games, ...
I know that due to JS code, Chrome limits timer to 4ms resolution. Alternative, when I played music on windows, the timer is 1ms resolution, with my knowledge, we only can set lower value for processes on windows. How can I set 2ms when I open Chrome or play media on windows. Thank you.

**Comment by amitxv** [comment]
If media player is requesting 1ms then you can't have it request 2ms (unless you patch the binary/edit the source code), it’s not last-call-sets-the-rules, it’s lowest-request-sets-the-rules.

- You can use SetTimerResolution in this repository to raise the resolution on a global level on Windows 10 1909 and under.

- Microsoft made it so that in Windows 10 2004+ timer resolution does not affect other processes so this isn't applicable

- Then the registry key mentioned in the README was added to Windows Server 2022 and Windows 11 to restore the implementation again prior to Windows 10 2004
