### ISSUE TITLE
Windows 10 22H2 actually change Slept(1) and Delta with Software Open

### ISSUE THREAD

**Issue by angelooo18** [amitxv/TimerResolution#5]
Hello, I enter the regedit key and reset my Windows Timer Resolution and settings the TimerTool to 0.5070ms the Slept(1) and Deltas are high, but when I open DPCchecker the values goes down like Windows 11. (By the way I wanted to ask you what exactly version of Windows 10 2004 version do you recommend to use TimerTool+regedit key in your tests).

0.5070ms without DPCchecker:
![image](https://github.com/amitxv/TimerResolution/assets/51036845/328d3f3b-3aec-4947-b201-3e9c460be919)

0.5070ms with DPCchecker On (Runing or not the values applies):
![image](https://github.com/amitxv/TimerResolution/assets/51036845/af0d2198-4765-4785-9af9-0acaa79c9c68)

**Comment by amitxv** [comment]
DPC Latency Checker raises the resolution in kernel-mode which is why precision increases despite the lack of the global behaviour.

Top is while the program is open, bottom is while it is closed.

![image](https://github.com/amitxv/TimerResolution/assets/86924251/1863a0da-9ed5-4921-85c1-152c63f1b0e9)

>By the way I wanted to ask you what exactly version of Windows 10 2004 version do you recommend to use TimerTool+regedit key in your tests.

The registry key is not supported on Windows 10 2004. Please read [this](https://github.com/amitxv/PC-Tuning/blob/main/docs/research.md#fixing-timing-precision-in-windows-after-the-great-rule-change).
